name: 'Deploy to AWS S3'
description: 'Deploy a static website to AWS S3 bucket'
runs:
  using: 'node20' # Specify the runtime environment as this is a JavaScript custom action
  main: .'main.js'  # name of the file that contains the action's code

